#-------------------------------------#
#              * scDRS *              #
#         Gene set enrichment         #
#-------------------------------------#
# 1 create gene set (config generated by gwas summary)
magma=/public/home/shilulu/software/MAGMA_v1.10/magma
eur="/public/share/wchirdzhq2022/Wulab_share/1000GenomePhase3_Ref_hg37/g1000_eur/g1000_eur"
geneloc="/public/home/shilulu/software/MAGMA_v1.10/NCBI37.3.SYMB.gene.loc"
prefix=$(basename "$eur")

#- gene annotation
qsubshcom "$magma --annotate window=35,10 \
--snp-loc $eur.bim \
--gene-loc $geneloc \
--out $prefix" 1 100G magma 1:00:00 ""

#- SNP p extract
gwas="/public/home/shilulu/Wulab/sll/ARHL/NC_sup_test/01.meta/All_MVP_Trpchevska_De-Angelis_BBJ_filter.txt"
trait="ARHL"
awk 'NR > 1 {print $1"\t"$7"\t"$8}' $gwas > $trait.pval

#- gene-based association study
qsubshcom "$magma --bfile $eur \
--pval $trait.pval ncol=3 \
--gene-annot $prefix.genes.annot
--out $trait" 1 100G magma 1:00:00 ""


# extract GENE and ZSCORE of trait
awk 'NR==1 {print "GENE\tARHL"} NR>1 {print $1"\t"$8}' $trait.genes.out > $trait.geneset.zscore

# 2 munge gene sets
conda activate scdrs

qsubshcom "scdrs munge-gs \
    --out-file ${trait}.scdrs \
    --zscore-file ${trait}.geneset.zscore \
    --weight zscore \
    --n-max 1000" 1 10G scdrs_munge 1:00:00 ""

Jean="/public/home/shilulu/Wulab_project/ARHL/NC_sup_test/08.scEnrich/Jean/scDRS/Jean_et_al.h5ad"

expr=$Milon
geneset="/public/home/shilulu/Wulab_project/ARHL/NC_sup_test/08.scEnrich/config/ARHL.scdrs"
qsubshcom "scdrs compute-score \
    --h5ad-file $expr \
    --h5ad-species mouse \
    --gs-file $geneset \
    --gs-species human \
    --flag-filter-data True \
    --flag-raw-count False \
    --flag-return-ctrl-raw-score False \
    --flag-return-ctrl-norm-score True \
    --out-folder ./" 1 100G scdrs 90:00:00 ""

# for cell type level
expr=$Sun1_2
qsubshcom "scdrs perform-downstream \
    --h5ad-file $expr \
    --score-file ./ARHL.full_score.gz \
    --group-analysis CellType \
    --flag-filter-data True \
    --flag-raw-count False \
    --out-folder ./" 1 100G scdrs 90:00:00 ""

# assoc_mcp: significance of cell type-disease association
# hetero_mcp: significance heterogeneity in association with disease across individual cells within a given cell type
# n_fdr_0.1: number of significantly associated cells (with FDR 0.1 across all cells for a given disease)



# 4. plot scDRS
dict_score = {
    trait: pd.read_csv(f"single_cell_data/cwy/{trait}.full_score.gz", sep="\t", index_col=0)
    for trait in df_gs.index}

for trait in dict_score:
    adata.obs[trait] = dict_score[trait]["norm_score"]

sc.set_figure_params(figsize=[2.5, 2.5], dpi=150)
sc.pl.umap(
    adata,
    color="level1class",
    ncols=1,
    color_map="RdBu_r",
    vmin=-5,
    vmax=5)

sc.pl.umap(
    adata,
    color=dict_score.keys(),
    color_map="RdBu_r",
    vmin=-5,
    vmax=5,
    s=20)